#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelStudent
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Hostel")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HostelStudent.Properties.Settings.Default.HostelConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.up_sel_getDepartments")]
		public ISingleResult<up_sel_getDepartmentsResult> up_sel_getDepartments()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_sel_getDepartmentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.up_sel_getInfoGroup")]
		public ISingleResult<up_sel_getInfoGroupResult> up_sel_getInfoGroup()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_sel_getInfoGroupResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.up_sel_getInfoRooms")]
		public ISingleResult<up_sel_getInfoRoomsResult> up_sel_getInfoRooms()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_sel_getInfoRoomsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.up_sel_getTypeRooms")]
		public ISingleResult<up_sel_getTypeRoomsResult> up_sel_getTypeRooms()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_sel_getTypeRoomsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.up_sel_getUsers")]
		public ISingleResult<up_sel_getUsersResult> up_sel_getUsers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<up_sel_getUsersResult>)(result.ReturnValue));
		}
	}
	
	public partial class up_sel_getDepartmentsResult
	{
		
		private string _InfoName;
		
		public up_sel_getDepartmentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string InfoName
		{
			get
			{
				return this._InfoName;
			}
			set
			{
				if ((this._InfoName != value))
				{
					this._InfoName = value;
				}
			}
		}
	}
	
	public partial class up_sel_getInfoGroupResult
	{
		
		private int _GroupId;
		
		private string _Group_name;
		
		private string _Department_name;
		
		private string _Curator_group;
		
		private string _Tel_number;
		
		public up_sel_getInfoGroupResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group name]", Storage="_Group_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Group_name
		{
			get
			{
				return this._Group_name;
			}
			set
			{
				if ((this._Group_name != value))
				{
					this._Group_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Department name]", Storage="_Department_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Department_name
		{
			get
			{
				return this._Department_name;
			}
			set
			{
				if ((this._Department_name != value))
				{
					this._Department_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Curator group]", Storage="_Curator_group", DbType="VarChar(100)")]
		public string Curator_group
		{
			get
			{
				return this._Curator_group;
			}
			set
			{
				if ((this._Curator_group != value))
				{
					this._Curator_group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tel number]", Storage="_Tel_number", DbType="VarChar(50)")]
		public string Tel_number
		{
			get
			{
				return this._Tel_number;
			}
			set
			{
				if ((this._Tel_number != value))
				{
					this._Tel_number = value;
				}
			}
		}
	}
	
	public partial class up_sel_getInfoRoomsResult
	{
		
		private int _RoomId;
		
		private string _TypeRoomName;
		
		private string _Number;
		
		private int _FloorApartment;
		
		private int _NumberBeds;
		
		public up_sel_getInfoRoomsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomId", DbType="Int NOT NULL")]
		public int RoomId
		{
			get
			{
				return this._RoomId;
			}
			set
			{
				if ((this._RoomId != value))
				{
					this._RoomId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeRoomName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeRoomName
		{
			get
			{
				return this._TypeRoomName;
			}
			set
			{
				if ((this._TypeRoomName != value))
				{
					this._TypeRoomName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this._Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FloorApartment", DbType="Int NOT NULL")]
		public int FloorApartment
		{
			get
			{
				return this._FloorApartment;
			}
			set
			{
				if ((this._FloorApartment != value))
				{
					this._FloorApartment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberBeds", DbType="Int NOT NULL")]
		public int NumberBeds
		{
			get
			{
				return this._NumberBeds;
			}
			set
			{
				if ((this._NumberBeds != value))
				{
					this._NumberBeds = value;
				}
			}
		}
	}
	
	public partial class up_sel_getTypeRoomsResult
	{
		
		private string _InfoName;
		
		public up_sel_getTypeRoomsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string InfoName
		{
			get
			{
				return this._InfoName;
			}
			set
			{
				if ((this._InfoName != value))
				{
					this._InfoName = value;
				}
			}
		}
	}
	
	public partial class up_sel_getUsersResult
	{
		
		private int _UserId;
		
		private string _FullName;
		
		private string _TelNumber;
		
		public up_sel_getUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TelNumber
		{
			get
			{
				return this._TelNumber;
			}
			set
			{
				if ((this._TelNumber != value))
				{
					this._TelNumber = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
